/* AUTO-GENERATED by UroExplorer admin. Edit via the admin panel, not by hand. */
window.__ABOUT__ = [
  "安徽医科大学第一附属医院/生命科学学院双聘副教授，第一附属医院团委副书记。",
  "中华医学会泌尿外科学分会智慧外科学组委员，中国性学会青少年性健康教育分会委员。美国罗切斯特大学访问学者，中国科学技术大学博士后，安徽省高校优青，合肥市 D 类高层次人才。"
];
