/**
 * Publication list — single source of truth.
 */
window.__PUBS_VERSION__ = 2;
window.__PUBS__ = [
  {
    "year": 2025,
    "title": "Comprehensive genomic insights into the genetic causality and comorbidity in urological cancers.",
    "authors": "Xiangyu Zhang #, Feixiang Yang #, Junyue Tao #, Kun Wang, Ke Xu, Tianrui Liu, Jiapeng Chen, Hao Li, Andong Cheng, Yiding Chen, Peng Guo*, Jialin Meng*",
    "journal": "NPJ Precision Oncology",
    "volume": "10(1):30",
    "type": "Article",
    "role": "corresponding",
    "if": 8,
    "casZone": 1,
    "jcrZone": 1,
    "isTop": false,
    "doi": "10.1038/s41698-025-01235-7",
    "link": "",
    "image": "https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41698-025-01235-7/MediaObjects/41698_2025_1235_Fig8_HTML.png?as=webp"
  },
  {
    "year": 2025,
    "title": "Multivariate genome-wide analysis of sarcopenia reveals genetic comorbidity with urological diseases.",
    "authors": "Yang Feixiang#, Zhang Xiangyu#, Dai Wei#, Xu Ke, Mei Yunyun, Liu Tianrui, Wang Kun, Liang Qianjun, Guo Peng, Liang Chaozhao*, Meng Jialin*",
    "journal": "Experimental Gerontology",
    "volume": "206:112783",
    "type": "Article",
    "role": "corresponding",
    "if": 3.3,
    "casZone": 3,
    "jcrZone": 2,
    "isTop": false,
    "doi": "https://doi.org/10.1016/j.exger.2025.112783",
    "link": "",
    "image": "https://ars.els-cdn.com/content/image/1-s2.0-S0531556525001123-gr2.jpg"
  },
  {
    "year": 2025,
    "title": "IGF1R Promotes Th17/Treg Cell Development in Experimental Autoimmune Prostatitis.",
    "authors": "Yu Guan#, Yue Shaoyu#, Chen Yiding#, Cheng Andong, Li Hao, Yang Feixiang, Liu Yi, Liang Chaozhao*, Meng Jialin*",
    "journal": "Journal of Inflammation Research",
    "volume": "18:5759–5775",
    "type": "Article",
    "role": "corresponding",
    "if": 4.2,
    "casZone": 3,
    "jcrZone": 2,
    "isTop": false,
    "doi": "10.2147/jir.s508576",
    "link": "",
    "image": "https://www.dovepress.com/file/img/graphical_abstract/508576/xlarge"
  },
  {
    "year": 2025,
    "title": "Sex hormones, blood metabolites and proteins mediating the causal associations between gut microbiota and prostatic diseases: evidences from Mendelian randomization study.",
    "authors": "Liu Tianrui#, Yang Feixiang#, Wang Zhige, Mei Yunyun, Li Hao, Wang Kun, Zhang Xiangyu, Chen Yiding, Zhang Yang*, Meng Jialin*",
    "journal": "Prostate International",
    "volume": "13(1):49-59",
    "type": "Article",
    "role": "corresponding",
    "if": 2.7,
    "casZone": 2,
    "jcrZone": 2,
    "isTop": false,
    "doi": "10.1016/j.prnil.2024.11.004",
    "link": "",
    "image": "https://ars.els-cdn.com/content/image/1-s2.0-S2287888224000862-gr1.jpg"
  },
  {
    "year": 2024,
    "title": "Insights from Immunomics and Metabolomics on the Associations between Prostatic Diseases and COVID-19.",
    "authors": "Yang Feixiang#, Guo Peng#, Wang Kun, Zhang Xiangyu, Hu Zhehao, Lou Qiyue, Ge Qintao, Chen Yiding, Liang Chaozhao*, Meng Jialin*",
    "journal": "Prostate International",
    "volume": "12(3):167-177",
    "type": "Article",
    "role": "corresponding",
    "if": 2.7,
    "casZone": 2,
    "jcrZone": 2,
    "isTop": false,
    "doi": "10.1016/j.prnil.2024.07.003",
    "link": "",
    "image": "https://ars.els-cdn.com/content/image/1-s2.0-S2287888224000540-ga1_lrg.jpg"
  },
  {
    "year": 2024,
    "title": "Deciphering the suppressive immune microenvironment of prostate cancer based on CD4+ regulatory T cells: Implications for prognosis and therapy prediction.",
    "authors": "Ge Qintao#, Zhao Zhijie#, Li Xiao#, Yang Feixiang, Zhang Meng, Hao Zongyao, Liang Chaozhao, Meng Jialin*",
    "journal": "Clinical and Translational Medicine",
    "volume": "14(1):e1552",
    "type": "Article",
    "role": "corresponding",
    "if": 7.9,
    "casZone": 1,
    "jcrZone": 1,
    "isTop": true,
    "doi": "10.1002/ctm2.1552",
    "link": ""
  },
  {
    "year": 2024,
    "title": "Comment on 'Systematic Druggable Genome-Wide Mendelian Randomization Identifies Therapeutic Targets for Sarcopenia' by Yin Et Al.",
    "authors": "Liu Tianrui, Yang Feixiang, Wang Kun, Guo Peng*, Meng Jialin*",
    "journal": "J Cachexia Sarcopenia Muscle",
    "volume": "",
    "type": "Letter",
    "role": "co-corresponding",
    "if": 9.4,
    "casZone": 1,
    "jcrZone": 1,
    "isTop": false,
    "doi": "10.1002/jcsm.13589",
    "link": ""
  },
  {
    "year": 2023,
    "title": "Multiomics characterization and verification of clear cell renal cell carcinoma molecular subtypes to guide precise chemotherapy and immunotherapy.",
    "authors": "Meng Jialin#, Jiang Aimin, Lu Xiaofan, Gu Di, Ge Qintao, Bai Suwen, Zhou Yundong, Zhou Jun, Hao Zongyao, Yan Fangrong, Wang Linhui, Wang Haitao, Du Juan, Liang Chaozhao",
    "journal": "Imeta",
    "volume": "2(4):e147",
    "type": "Article",
    "role": "first",
    "if": 23.7,
    "casZone": 1,
    "jcrZone": 1,
    "isTop": false,
    "doi": "10.1002/imt2.147",
    "link": ""
  },
  {
    "year": 2023,
    "title": "Non-coding RNAs: Emerging roles in the characterization of immune microenvironment and immunotherapy of prostate cancer.",
    "authors": "Feixiang Yang#, Jiawei Li#, Qintao Ge, Yuchen Zhang, Meng Zhang, Jun Zhou, Haitao Wang, Juan Du, Shenglin Gao, Chaozhao Liang, Meng Jialin*",
    "journal": "Biochemical Pharmacology",
    "volume": "214:115669",
    "type": "Review",
    "role": "corresponding",
    "if": 5.3,
    "casZone": 2,
    "jcrZone": 1,
    "isTop": false,
    "doi": "10.1016/j.bcp.2023.115669",
    "link": ""
  },
  {
    "year": 2023,
    "title": "TIMEAS, a promising method for the stratification of testicular germ cell tumor patients with distinct immune microenvironment, clinical outcome and sensitivity to frontline therapies.",
    "authors": "Meng Jialin#, Gao Jingjing#, Li Xiao#, Gao Rui, Lu Xiaofan, Zhou Jun, Yan Fangrong, Wang Haitao, Liu Yi, Hao Zongyao*, Zhang Xiansheng*, Liang Chaozhao*",
    "journal": "Cellular Oncology",
    "volume": "46(3):745-759",
    "type": "Article",
    "role": "first",
    "if": 4.9,
    "casZone": 1,
    "jcrZone": 2,
    "isTop": false,
    "doi": "10.1007/s13402-023-00781-1",
    "link": ""
  },
  {
    "year": 2023,
    "title": "Molecular classifications of prostate cancer: basis for individualized risk stratification and precision therapy.",
    "authors": "Qintao Ge#, Jiawei Li#, Feixiang Yang, Xuefeng Tian, Meng Zhang, Zongyao Hao, Chaozhao Liang* & Jialin Meng*",
    "journal": "Annals of Medicine",
    "volume": "55:2279235",
    "type": "Review",
    "role": "co-corresponding",
    "if": 4.9,
    "casZone": 2,
    "jcrZone": 1,
    "isTop": false,
    "doi": "10.1080/07853890.2023.2279235",
    "link": ""
  },
  {
    "year": 2022,
    "title": "Protective trend of anti-androgen therapy during the COVID-19 pandemic: A meta-analysis.",
    "authors": "Meng Jialin#, Ge Qintao#, Li Jiawei#, Lu Xiaofan, Chen Yonghao, Wang Haitao, Zhang Meng, Du Juan, Zhang Li, Hao Zongyao, Liang Chaozhao",
    "journal": "Journal of Infection",
    "volume": "84(6):834-872",
    "type": "Letter",
    "role": "first",
    "if": 14.3,
    "casZone": 1,
    "jcrZone": 1,
    "isTop": true,
    "doi": "10.1016/j.jinf.2022.03.020",
    "link": ""
  },
  {
    "year": 2022,
    "title": "Metabolomics analysis reveals the differential metabolites and establishes the therapeutic effect prediction nomogram among CP/CPPS patients who respond or do not respond to LiST.",
    "authors": "Meng Jialin#, Jin Chen#, Li Jiawei, Zhang Song, Zhang Meng, Hao Zongyao, Chen Xianguo*, Zhang Li*, Liang Chaozhao*",
    "journal": "Frontiers in Immunology",
    "volume": "13:953403",
    "type": "Article",
    "role": "first",
    "if": 5.7,
    "casZone": 2,
    "jcrZone": 1,
    "isTop": true,
    "doi": "10.3389/fimmu.2022.953403",
    "link": ""
  },
  {
    "year": 2022,
    "title": "Macrophages and monocytes mediated activation of oxidative phosphorylation implicated the prognosis and clinical therapeutic strategy of Wilms tumour.",
    "authors": "Jialin Meng#, Yonghao Chen#, Xiaofan Lu#, Qintao Ge, Feixiang Yang, Suwen Bai, Chaozhao Liang*, Juan Du*",
    "journal": "Computational and Structural Biotechnology Journal",
    "volume": "",
    "type": "Article",
    "role": "first",
    "if": 4.4,
    "casZone": 2,
    "jcrZone": 2,
    "isTop": false,
    "doi": "10.1016/j.csbj.2022.06.052",
    "link": ""
  },
  {
    "year": 2022,
    "title": "Risk subtyping and prognostic assessment of prostate cancer based on consensus genes.",
    "authors": "Meng Jialin#, Guan Yu#, Wang Bijun, Chen Lei, Chen Junyi, Zhang Meng, Liang Chaozhao",
    "journal": "Communications Biology",
    "volume": "5(1):233",
    "type": "Article",
    "role": "first",
    "if": 5.2,
    "casZone": 1,
    "jcrZone": 1,
    "isTop": false,
    "doi": "10.1038/s42003-022-03164-8",
    "link": ""
  },
  {
    "year": 2021,
    "title": "Integrated Multi-Omics Data Reveals the Molecular Subtypes and Guides the Androgen Receptor Signaling Inhibitor Treatment of Prostate Cancer.",
    "authors": "Meng Jialin#, Lu Xiaofan#, Jin Chen#, Zhou Yujie, Ge Qintao, Zhou Jun, Hao Zongyao, Yan Fangrong*, Zhang Meng*, Liang Chaozhao*",
    "journal": "Clinical and Translational Medicine",
    "volume": "11(12):e655",
    "type": "Letter",
    "role": "first",
    "if": 7.9,
    "casZone": 1,
    "jcrZone": 1,
    "isTop": false,
    "doi": "10.1002/ctm2.655",
    "link": ""
  },
  {
    "year": 2021,
    "title": "Immune Response Drives Outcomes in Prostate Cancer: Implications for Immunotherapy.",
    "authors": "Meng Jialin#, Zhou Yujie, Lu Xiaofan, Bian Zichen, Chen Yiding, Zhou Jun, Zhang Li, Hao Zongyao, Zhang Meng*, Liang Chaozhao*",
    "journal": "Molecular Oncology",
    "volume": "15(5):1358-1375",
    "type": "Article",
    "role": "first",
    "if": 5,
    "casZone": 2,
    "jcrZone": 1,
    "isTop": false,
    "doi": "10.1002/1878-0261.12887",
    "link": ""
  },
  {
    "year": 2021,
    "title": "Tumor immune microenvironment-based classifications of bladder cancer for enhancing the response rate of immunotherapy.",
    "authors": "Meng Jialin#, Lu Xiaofan#, Zhou Yujie#, Zhang Meng, Ge Qintao, Zhou Jun, Hao Zongyao, Gao Shenglin*, Yan Fangrong*, Liang Chaozhao*",
    "journal": "Molecular Therapy-Oncolytics",
    "volume": "20:410-421",
    "type": "Article",
    "role": "first",
    "if": 5.3,
    "casZone": 2,
    "jcrZone": 2,
    "isTop": false,
    "doi": "10.1016/j.omto.2021.02.001",
    "link": ""
  },
  {
    "year": 2020,
    "title": "Characterization of the prognostic values and response to immunotherapy/chemotherapy of Krüppel-like factors in prostate cancer.",
    "authors": "Meng Jialin#, Lu Xiaofan#, Zhou Yujie#, Zhang Meng, Gao Lei, Gao Shenglin*, Yan Fangrong*, Liang Chaozhao*",
    "journal": "Journal of Cellular and Molecular Medicine",
    "volume": "24(10):5797-5810",
    "type": "Article",
    "role": "first",
    "if": 4.3,
    "casZone": 2,
    "jcrZone": 2,
    "isTop": false,
    "doi": "10.1111/jcmm.15242",
    "link": ""
  },
  {
    "year": 2020,
    "title": "The prevalence and risk factors of prostatic calculi in Han Chinese: a cross-sectional study based on health examinations.",
    "authors": "Meng Jialin#, Zhang Meng#, Guan Shi-Yang, Zhou Jun, Fan Song, Hu Huaqing*, Liang Chaozhao*, et al.",
    "journal": "The Aging Male",
    "volume": "23(5):887-892",
    "type": "Article",
    "role": "first",
    "if": 2.7,
    "casZone": 4,
    "jcrZone": 2,
    "isTop": false,
    "doi": "10.1080/13685538.2019.1620203",
    "link": ""
  },
  {
    "year": 2020,
    "title": "Systematic investigation of the prognostic value of cell division cycle-associated proteins for clear cell renal cell carcinoma patients.",
    "authors": "Meng Jialin#, Gao Lei#, Zhang Meng, Gao Shenglin*, Fan Song*, Liang Chaozhao",
    "journal": "Biomarkers in Medicine",
    "volume": "14(3):223-238",
    "type": "Article",
    "role": "first",
    "if": 1.9,
    "casZone": 4,
    "jcrZone": 3,
    "isTop": false,
    "doi": "10.2217/bmm-2019-0498",
    "link": ""
  },
  {
    "year": 2019,
    "title": "The establishment of immune infiltration based novel recurrence predicting nomogram in prostate cancer.",
    "authors": "Meng Jialin#, Liu Yi, Guan Shiyang, Fan Song, Zhou Jun, Zhang Meng*, & Liang Chaozhao*",
    "journal": "Cancer Medicine",
    "volume": "8(11):5202-5213",
    "type": "Article",
    "role": "first",
    "if": 2.9,
    "casZone": 2,
    "jcrZone": 2,
    "isTop": false,
    "doi": "10.1002/cam4.2433",
    "link": ""
  },
  {
    "year": 2019,
    "title": "A novel frameshift PKD1 mutation in a Chinese patient with autosomal dominant polycystic kidney disease and azoospermia: A case report.",
    "authors": "Meng Jialin#, Xu Yuchen, Shen Xufeng, Liang Chaozhao*",
    "journal": "Experimental and Therapeutic Medicine",
    "volume": "17(1):507-511",
    "type": "Article",
    "role": "first",
    "if": 2.4,
    "casZone": 4,
    "jcrZone": 3,
    "isTop": false,
    "doi": "10.3892/etm.2018.6946",
    "link": ""
  },
  {
    "year": 2019,
    "title": "Age, height, BMI and FBG, the predicting biomarkers of prostate volume among aging benign prostatic hyperplasia: evidence from 5285 patients.",
    "authors": "Meng Jialin#, Liu Yi, Guan Shiyang, Ma Huiya, Zhang Xiaoyu, Fan Song, Hu Huaqing, Zhang Meng*, Liang Chaozhao*",
    "journal": "International Journal of Clinical Practice",
    "volume": "73(12):e13438",
    "type": "Article",
    "role": "first",
    "if": 2.2,
    "casZone": 4,
    "jcrZone": 2,
    "isTop": false,
    "doi": "10.1111/ijcp.13438",
    "link": ""
  },
  {
    "year": 2018,
    "title": "TP73 G4C14-A4T14 Polymorphism and Cancer Susceptibility: Evidence from 36 case-control studies.",
    "authors": "Meng Jialin#, Wang Shuo, Zhang Meng, Fan Song, Zhang Li*, Liang Chaozhao*",
    "journal": "Bioscience Reports",
    "volume": "38(6):BSR20181452",
    "type": "Article",
    "role": "first",
    "if": 3.8,
    "casZone": 3,
    "jcrZone": 2,
    "isTop": false,
    "doi": "10.1042/BSR20181452",
    "link": ""
  },
  {
    "year": 2018,
    "title": "Clinical Features of 167 Inpatients with Autosomal Dominant Polycystic Kidney Disease at a Single Center in China.",
    "authors": "Meng Jialin#, Xu Yuchen#, Li Ao, Fan Song, Shen Xufeng, Ma Dongyue, Zhang Li, Hao Zongyao, Zhang Xiansheng, Liang Chaozhao*",
    "journal": "Medical Science Monitor",
    "volume": "24:6498-6505",
    "type": "Article",
    "role": "first",
    "if": 2.2,
    "casZone": 4,
    "jcrZone": 3,
    "isTop": false,
    "doi": "10.12659/MSM.910127",
    "link": ""
  },
  {
    "year": 2018,
    "title": "Polymorphism of MMP-9 gene is not associated with the risk of urinary cancers: Evidence from an updated meta-analysis.",
    "authors": "Meng Jialin#, Wang Shuo#, Shen Xufeng, Bai Zhengming, Niu Qingsong, Ma Dongyue, Xu Yuchen, Liang Chaozhao*",
    "journal": "Pathology Research and Practice",
    "volume": "214(12):1966-1973",
    "type": "Article",
    "role": "first",
    "if": 2.9,
    "casZone": 4,
    "jcrZone": 2,
    "isTop": false,
    "doi": "10.1016/j.prp.2018.09.011",
    "link": ""
  },
  {
    "year": 2018,
    "title": "An update meta-analysis and systematic review of TAP polymorphisms as potential biomarkers for judging cancer risk.",
    "authors": "Meng Jialin#, Li Wanzhen#, Zhang Meng, Hao Zongyao, Fan Song, Zhang Li, Liang Chaozhao*",
    "journal": "Pathology Research and Practice",
    "volume": "214(10):1556-1563",
    "type": "Article",
    "role": "first",
    "if": 2.9,
    "casZone": 4,
    "jcrZone": 2,
    "isTop": false,
    "doi": "10.1016/j.prp.2018.07.018",
    "link": ""
  },
  {
    "year": 2018,
    "title": "Do polymorphisms in protein kinase catalytic subunit alpha-1 gene associated with cancer susceptibility? a meta-analysis and systematic review.",
    "authors": "Meng Jialin#, Fan Xinyao, Zhang Meng, Hao Zongyao, Liang Chaozhao*",
    "journal": "BMC Medical Genetics",
    "volume": "19(1):189",
    "type": "Article",
    "role": "first",
    "if": 2.02,
    "casZone": 4,
    "jcrZone": 4,
    "isTop": false,
    "doi": "10.1186/s12881-018-0704-8",
    "link": ""
  }
];
