/* AUTO-GENERATED by UroExplorer admin. Edit via the admin panel, not by hand. */
window.__TEAM__ = [
  {
    "slug": "master-lisi",
    "role": "master",
    "name": {
      "zh": "李四",
      "en": "Li Si"
    },
    "title": {
      "zh": "硕士研究生 · 2024 级",
      "en": "Master Student · Class of 2024"
    },
    "affil": {
      "zh": "安徽医科大学",
      "en": "Anhui Medical University"
    },
    "email": "",
    "photo": "",
    "about": {
      "zh": [
        "（个人简介待补充）"
      ],
      "en": [
        "(Bio pending)"
      ]
    },
    "education": [],
    "experience": [],
    "publications": [],
    "awards": [],
    "social": {}
  },
  {
    "slug": "ug-wangwu",
    "role": "ug",
    "name": {
      "zh": "王五",
      "en": "Wang Wu"
    },
    "title": {
      "zh": "本科生 · 临床医学 · 2022 级",
      "en": "Undergraduate · Clinical Medicine · Class of 2022"
    },
    "affil": {
      "zh": "安徽医科大学",
      "en": "Anhui Medical University"
    },
    "email": "",
    "photo": "",
    "about": {
      "zh": [
        "（个人简介待补充）"
      ],
      "en": [
        "(Bio pending)"
      ]
    },
    "education": [],
    "experience": [],
    "publications": [],
    "awards": [],
    "social": {}
  },
  {
    "slug": "phd-yangfeixiang",
    "role": "phd",
    "name": {
      "zh": "杨飞翔",
      "en": "Yang Feixiang"
    },
    "title": {
      "zh": "",
      "en": ""
    },
    "affil": {
      "zh": "",
      "en": ""
    },
    "email": "",
    "photo": "",
    "about": {
      "zh": [],
      "en": []
    },
    "education": [],
    "experience": [],
    "projects": [],
    "publications": [],
    "awards": [],
    "social": {
      "scholar": "",
      "orcid": "",
      "researchgate": "",
      "github": ""
    }
  },
  {
    "slug": "copi-guanyu",
    "role": "copi",
    "name": {
      "zh": "关煜",
      "en": "Guan Yu"
    },
    "title": {
      "zh": "",
      "en": ""
    },
    "affil": {
      "zh": "",
      "en": ""
    },
    "email": "",
    "photo": "",
    "about": {
      "zh": [],
      "en": []
    },
    "education": [],
    "experience": [],
    "projects": [],
    "publications": [],
    "awards": [],
    "social": {
      "scholar": "",
      "orcid": "",
      "researchgate": "",
      "github": ""
    }
  }
];
