/* AUTO-GENERATED by UroExplorer admin. Edit via the admin panel, not by hand. */
window.__TOOLS__ = [
  {
    "name": "panelpack",
    "type": "Claude Skill · Python CLI",
    "link": "https://github.com/AHMUJia/panelpack",
    "image": "assets/img/tools/panelpack.svg",
    "description": "One-command tool that composes sub-figure files (PDF / PNG / JPG / TIFF) into publication-ready composite figures. Automatically adds A / B / C / D panel labels, supports flexible layouts (rows, columns, aspect ratios, gaps), and produces R/ggplot2 physical-size recommendations — eliminating manual alignment and redrawing.<br><br>Use cases: multi-panel Figure assembly, reviewer-requested re-layouts, and conference poster composition."
  }
];
