/**
 * UroExplorer admin backend.
 *
 * Auth model:
 *   - Sign-in form posts {username, password}; backend verifies bcrypt hash
 *     stored in /data/users.json, issues HMAC-signed session cookie.
 *   - role="admin" can edit any section, manage users.
 *   - role="member" can only PUT/GET its own team entry (matched by memberSlug).
 *
 * Storage:
 *   - Source of truth = JSON files under DATA_DIR
 *   - On every PUT, the matching *-data.js in SITE_DIR is regenerated.
 *   - On startup the JS files are also regenerated from JSON (idempotent — fixes
 *     drift after a `git pull` that may have replaced *-data.js with stale copies).
 *
 * Required env: SESSION_SECRET (a long random string).
 */
import express from 'express';
import cookieParser from 'cookie-parser';
import multer from 'multer';
import bcrypt from 'bcryptjs';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { SECTIONS } from './sections.js';

const SITE_DIR = process.env.SITE_DIR || path.resolve('..');
const DATA_DIR = process.env.DATA_DIR || path.resolve('./data');
const PHOTO_DIR = path.join(SITE_DIR, 'assets/img/team');
const PORT = Number(process.env.PORT) || 3000;
const SESSION_SECRET = process.env.SESSION_SECRET;
const SESSION_TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

if (!SESSION_SECRET || SESSION_SECRET.length < 16) {
  console.error('FATAL: SESSION_SECRET env var must be set (≥16 chars).');
  process.exit(1);
}

await fs.mkdir(DATA_DIR, { recursive: true });
await fs.mkdir(PHOTO_DIR, { recursive: true });

/* ============================================================
   Sessions — signed cookie, no DB
   ============================================================ */
function signToken(payload) {
  const enriched = { ...payload, exp: Date.now() + SESSION_TTL_MS };
  const data = Buffer.from(JSON.stringify(enriched)).toString('base64url');
  const sig = crypto.createHmac('sha256', SESSION_SECRET).update(data).digest('base64url');
  return `${data}.${sig}`;
}
function verifyToken(token) {
  if (!token || typeof token !== 'string') return null;
  const dot = token.indexOf('.');
  if (dot < 0) return null;
  const data = token.slice(0, dot);
  const sig  = token.slice(dot + 1);
  const expected = crypto.createHmac('sha256', SESSION_SECRET).update(data).digest('base64url');
  let ok = false;
  try { ok = sig.length === expected.length && crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected)); }
  catch { ok = false; }
  if (!ok) return null;
  try {
    const payload = JSON.parse(Buffer.from(data, 'base64url').toString('utf-8'));
    if (!payload.exp || payload.exp < Date.now()) return null;
    return payload;
  } catch { return null; }
}

function authed(req, res, next) {
  const user = verifyToken(req.cookies?.session);
  if (!user) return res.status(401).json({ error: 'Not authenticated' });
  req.user = user;
  next();
}
function adminOnly(req, res, next) {
  if (req.user.role !== 'admin') return res.status(403).json({ error: 'Admin only' });
  next();
}

/* ============================================================
   Users — DATA_DIR/users.json
   shape: { [username]: { passwordHash, role: 'admin'|'member', memberSlug? } }
   ============================================================ */
const USERS_FILE = path.join(DATA_DIR, 'users.json');
async function loadUsers() {
  try { return JSON.parse(await fs.readFile(USERS_FILE, 'utf-8')); }
  catch (e) { if (e.code === 'ENOENT') return {}; throw e; }
}
async function saveUsers(users) {
  await fs.writeFile(USERS_FILE, JSON.stringify(users, null, 2), 'utf-8');
}

/* ============================================================
   Section data
   ============================================================ */
const JS_HEADER = '/* AUTO-GENERATED by UroExplorer admin. Edit via the admin panel, not by hand. */\n';
async function writeJsFile(file, varName, data) {
  const body = JS_HEADER + `window.${varName} = ${JSON.stringify(data, null, 2)};\n`;
  await fs.writeFile(file, body, 'utf-8');
}
async function readJsonOr(file, dflt) {
  try { return JSON.parse(await fs.readFile(file, 'utf-8')); }
  catch (e) { if (e.code === 'ENOENT') return dflt; throw e; }
}

async function readSection(name) {
  const cfg = SECTIONS[name];
  if (!cfg) throw new Error('Unknown section: ' + name);
  if (cfg.split) {
    return {
      zh: await readJsonOr(path.join(DATA_DIR, `${name}.zh.json`), []),
      en: await readJsonOr(path.join(DATA_DIR, `${name}.en.json`), [])
    };
  }
  const dflt = cfg.isObject ? {} : [];
  return await readJsonOr(path.join(DATA_DIR, `${name}.json`), dflt);
}

async function writeSection(name, data) {
  const cfg = SECTIONS[name];
  if (!cfg) throw new Error('Unknown section: ' + name);
  if (cfg.split) {
    if (!data || !Array.isArray(data.zh) || !Array.isArray(data.en))
      throw new Error('Bilingual section requires { zh: [], en: [] }');
    await fs.writeFile(path.join(DATA_DIR, `${name}.zh.json`), JSON.stringify(data.zh, null, 2));
    await fs.writeFile(path.join(DATA_DIR, `${name}.en.json`), JSON.stringify(data.en, null, 2));
    await writeJsFile(path.join(SITE_DIR, cfg.zhFile), cfg.var, data.zh);
    await writeJsFile(path.join(SITE_DIR, cfg.enFile), cfg.var, data.en);
  } else if (cfg.isObject) {
    if (data == null || typeof data !== 'object' || Array.isArray(data))
      throw new Error('Object section requires a plain object');
    await fs.writeFile(path.join(DATA_DIR, `${name}.json`), JSON.stringify(data, null, 2));
    await writeJsFile(path.join(SITE_DIR, cfg.file), cfg.var, data);
  } else {
    if (!Array.isArray(data)) throw new Error('Non-split section requires an array');
    await fs.writeFile(path.join(DATA_DIR, `${name}.json`), JSON.stringify(data, null, 2));
    await writeJsFile(path.join(SITE_DIR, cfg.file), cfg.var, data);
  }
}

/* On startup, regenerate every *-data.js from current JSON so the static site
   is in sync with the source of truth. Skips a section if its JSON is missing
   (first-time deploy: run `npm run migrate` once first). */
async function regenerateAllJs() {
  for (const [name, cfg] of Object.entries(SECTIONS)) {
    if (cfg.split) {
      const zhFile = path.join(DATA_DIR, `${name}.zh.json`);
      const enFile = path.join(DATA_DIR, `${name}.en.json`);
      if (await fileExists(zhFile)) {
        await writeJsFile(path.join(SITE_DIR, cfg.zhFile), cfg.var, await readJsonOr(zhFile, []));
      }
      if (await fileExists(enFile)) {
        await writeJsFile(path.join(SITE_DIR, cfg.enFile), cfg.var, await readJsonOr(enFile, []));
      }
    } else {
      const f = path.join(DATA_DIR, `${name}.json`);
      if (await fileExists(f)) {
        await writeJsFile(path.join(SITE_DIR, cfg.file), cfg.var, await readJsonOr(f, []));
      }
    }
  }
}
async function fileExists(f) {
  try { await fs.access(f); return true; } catch { return false; }
}

/* ============================================================
   App
   ============================================================ */
const app = express();
app.disable('x-powered-by');
app.set('trust proxy', 1); // Caddy sets X-Forwarded-* headers
app.use(express.json({ limit: '5mb' }));
app.use(cookieParser());

const cookieOpts = {
  httpOnly: true,
  sameSite: 'lax',
  secure: process.env.NODE_ENV !== 'development',
  maxAge: SESSION_TTL_MS,
  path: '/'
};

/* ----- Auth ----- */
app.post('/api/login', async (req, res) => {
  const { username, password } = req.body || {};
  if (typeof username !== 'string' || typeof password !== 'string')
    return res.status(400).json({ error: 'username and password required' });
  const users = await loadUsers();
  const u = users[username];
  if (!u || !await bcrypt.compare(password, u.passwordHash))
    return res.status(401).json({ error: 'Invalid credentials' });
  const token = signToken({ username, role: u.role, memberSlug: u.memberSlug || null });
  res.cookie('session', token, cookieOpts);
  res.json({ username, role: u.role, memberSlug: u.memberSlug || null });
});

app.post('/api/logout', (req, res) => {
  res.clearCookie('session', { path: '/' });
  res.json({ ok: true });
});

app.get('/api/me', authed, (req, res) => {
  res.json({ username: req.user.username, role: req.user.role, memberSlug: req.user.memberSlug || null });
});

app.post('/api/me/password', authed, async (req, res) => {
  const { oldPassword, newPassword } = req.body || {};
  if (typeof newPassword !== 'string' || newPassword.length < 6)
    return res.status(400).json({ error: 'New password must be at least 6 characters' });
  const users = await loadUsers();
  const u = users[req.user.username];
  if (!u) return res.status(404).json({ error: 'User not found' });
  if (!await bcrypt.compare(oldPassword || '', u.passwordHash))
    return res.status(401).json({ error: 'Old password incorrect' });
  u.passwordHash = await bcrypt.hash(newPassword, 12);
  users[req.user.username] = u;
  await saveUsers(users);
  res.json({ ok: true });
});

/* ----- Admin: section read/write ----- */
app.get('/api/data', authed, adminOnly, (req, res) => {
  res.json(Object.keys(SECTIONS));
});

app.get('/api/data/:section', authed, adminOnly, async (req, res, next) => {
  try {
    const { section } = req.params;
    if (!(section in SECTIONS)) return res.status(404).json({ error: 'Unknown section' });
    res.json(await readSection(section));
  } catch (e) { next(e); }
});

app.put('/api/data/:section', authed, adminOnly, async (req, res, next) => {
  try {
    const { section } = req.params;
    if (!(section in SECTIONS)) return res.status(404).json({ error: 'Unknown section' });
    await writeSection(section, req.body);
    res.json({ ok: true });
  } catch (e) { next(e); }
});

/* ----- Admin: user management ----- */
app.get('/api/users', authed, adminOnly, async (req, res) => {
  const users = await loadUsers();
  const sanitized = {};
  for (const [k, v] of Object.entries(users)) {
    sanitized[k] = { role: v.role, memberSlug: v.memberSlug || null };
  }
  res.json(sanitized);
});

app.put('/api/users/:username', authed, adminOnly, async (req, res, next) => {
  try {
    const { username } = req.params;
    if (!/^[a-z0-9_-]+$/i.test(username) || username.length > 32)
      return res.status(400).json({ error: 'Invalid username (use a-z, 0-9, _, -, max 32 chars)' });
    const { password, role, memberSlug } = req.body || {};
    if (role !== 'admin' && role !== 'member')
      return res.status(400).json({ error: 'role must be "admin" or "member"' });
    if (role === 'member' && (typeof memberSlug !== 'string' || !memberSlug))
      return res.status(400).json({ error: 'memberSlug is required when role=member' });

    const users = await loadUsers();
    const existing = users[username];
    let passwordHash;
    if (typeof password === 'string' && password.length >= 6) {
      passwordHash = await bcrypt.hash(password, 12);
    } else if (existing) {
      passwordHash = existing.passwordHash;
    } else {
      return res.status(400).json({ error: 'New user requires a password (≥ 6 chars)' });
    }
    users[username] = { passwordHash, role, ...(role === 'member' ? { memberSlug } : {}) };
    await saveUsers(users);
    res.json({ ok: true, username });
  } catch (e) { next(e); }
});

app.delete('/api/users/:username', authed, adminOnly, async (req, res) => {
  const { username } = req.params;
  if (username === req.user.username)
    return res.status(400).json({ error: 'Cannot delete the currently logged-in account' });
  const users = await loadUsers();
  if (!users[username]) return res.status(404).json({ error: 'User not found' });
  delete users[username];
  await saveUsers(users);
  res.json({ ok: true });
});

/* ----- Member self-edit ----- */
app.get('/api/me/member', authed, async (req, res, next) => {
  try {
    if (req.user.role === 'admin')
      return res.status(400).json({ error: 'Admin has no member slug; use /api/data/team' });
    const slug = req.user.memberSlug;
    if (!slug) return res.status(404).json({ error: 'No member slug bound to this account' });
    const team = await readSection('team');
    const m = team.find(x => x.slug === slug);
    if (!m) return res.status(404).json({ error: 'Member entry not found in team list — ask admin to recreate' });
    res.json(m);
  } catch (e) { next(e); }
});

app.put('/api/me/member', authed, async (req, res, next) => {
  try {
    if (req.user.role === 'admin')
      return res.status(400).json({ error: 'Admin should edit team via /api/data/team' });
    const slug = req.user.memberSlug;
    if (!slug) return res.status(404).json({ error: 'No member slug bound to this account' });
    const incoming = req.body || {};
    const team = await readSection('team');
    const idx = team.findIndex(x => x.slug === slug);
    if (idx === -1) return res.status(404).json({ error: 'Member entry not found' });
    /* Lock down: students cannot change slug or role. Force them to existing values. */
    const existing = team[idx];
    team[idx] = { ...incoming, slug, role: existing.role };
    await writeSection('team', team);
    res.json({ ok: true });
  } catch (e) { next(e); }
});

/* ----- Image upload -----
   /api/upload accepts a `dir` form field. Files are saved under
   SITE_DIR/assets/img/<dir>/. Frontend MUST append `dir` BEFORE `photo`
   in the FormData so multer.diskStorage destination sees it.
   - Members may only upload to dir=team and only with their own slug.
   - Admin may upload to any dir in the allowlist.
*/
const ALLOWED_UPLOAD_DIRS = new Set(['team', 'uploads']);

const upload = multer({
  storage: multer.diskStorage({
    destination: (req, file, cb) => {
      const dirRaw = (req.body && req.body.dir) || 'team';
      const safeDir = ALLOWED_UPLOAD_DIRS.has(dirRaw) ? dirRaw : 'team';
      const dest = path.join(SITE_DIR, 'assets/img', safeDir);
      fs.mkdir(dest, { recursive: true }).then(() => cb(null, dest)).catch(cb);
    },
    filename: (req, file, cb) => {
      const slugRaw = (req.body?.slug || req.user?.memberSlug || 'image').toString();
      const slug = slugRaw.replace(/[^a-z0-9-]/gi, '-').slice(0, 40).toLowerCase() || 'image';
      const extMap = { 'image/jpeg': '.jpg', 'image/png': '.png', 'image/webp': '.webp', 'image/gif': '.gif', 'image/svg+xml': '.svg' };
      const ext = extMap[file.mimetype] || '.bin';
      cb(null, `${slug}-${Date.now()}${ext}`);
    }
  }),
  limits: { fileSize: 5 * 1024 * 1024, files: 1 },
  fileFilter: (req, file, cb) => {
    if (/^image\/(jpeg|png|webp|gif|svg\+xml)$/.test(file.mimetype)) cb(null, true);
    else cb(new Error('Only JPEG, PNG, WebP, GIF, SVG allowed'));
  }
});

app.post('/api/upload', authed, (req, res, next) => {
  upload.single('photo')(req, res, async (err) => {
    if (err) return res.status(400).json({ error: err.message });

    const dir = (req.body && req.body.dir) || 'team';
    const fileToCleanup = req.file && req.file.path;
    const cleanup = async () => { if (fileToCleanup) { try { await fs.unlink(fileToCleanup); } catch {} } };

    if (!ALLOWED_UPLOAD_DIRS.has(dir)) {
      await cleanup();
      return res.status(400).json({ error: 'Unknown dir: ' + dir });
    }
    if (req.user.role !== 'admin') {
      if (dir !== 'team') {
        await cleanup();
        return res.status(403).json({ error: 'Only admin can upload to dir=' + dir });
      }
      if (req.body.slug && req.body.slug !== req.user.memberSlug) {
        await cleanup();
        return res.status(403).json({ error: 'Members can only upload their own photo' });
      }
    }
    if (!req.file) return res.status(400).json({ error: 'No file uploaded (field name: photo)' });
    const relPath = `assets/img/${dir}/${req.file.filename}`;
    res.json({ path: relPath, url: '/' + relPath });
  });
});

/* ----- Dev-only: serve static files (in production Caddy does this) ----- */
if (process.env.NODE_ENV === 'development') {
  app.use(express.static(SITE_DIR, { extensions: ['html'] }));
}

/* ----- Generic error handler (must come last) ----- */
app.use((err, req, res, next) => {
  console.error('[error]', req.method, req.originalUrl, '-', err);
  res.status(err.status || 500).json({ error: err.message || 'Server error' });
});

/* ----- Start ----- */
await regenerateAllJs().catch(e => console.warn('[startup] regenerate failed:', e.message));

app.listen(PORT, '0.0.0.0', () => {
  console.log(`UroExplorer admin listening on :${PORT}`);
  console.log(`  SITE_DIR=${SITE_DIR}`);
  console.log(`  DATA_DIR=${DATA_DIR}`);
});
